### ISSUE TITLE
When calling waitUntilWindowLoaded, webContents is not set in Application

### ISSUE THREAD

**Issue by burdeasa** [electron/spectron#174]
I'm seeing:
 **waitUntilWindowLoaded: Cannot read property 'isLoading' of undefined** 

This is the same issue as reported in issue 157, but that was closed, so I thought I would open a new issue.
See: https://github.com/electron/spectron/issues/157

I am using spectron 3.4.0 with electron 1.3.2, but I also tried spectron 3.3.0 and this made no difference for me.

After running a lot of tests and debugging, I am pretty convinced the issue is related to the following:

It appears that things work fine as long as the electron App under test creates AND loads its window immediately upon call to the app ready event handler.  However, if loading the window is deferred to perform some other processing first, the above error occurs consistently.

Just to be real clear here:

The following does not seem to have a problem:

<pre>
let mainWindow

app.on('ready', () => {
    mainWindow = new BrowserWindow({ 
        width: 1400, 
        height: 900,
        backgroundColor: '#EAECEE'
    })
    mainWindow.loadURL(`file://${__dirname}/index.html`)
})
</pre>

However, the following always seems to fail:
<pre>
let mainWindow

app.on('ready', () => {
    mainWindow = new BrowserWindow({ 
        width: 1400, 
        height: 900,
        backgroundColor: '#EAECEE'
    })
    setTimeout(() => {
        mainWindow.loadURL(`file://${__dirname}/index.html`)
    }, 2000)
})
</pre>

**Comment by samvloeberghs** [comment]
having related issues..

**Comment by Sigurthorb** [comment]
I am also having the same issue.
Doing a syncronous call to the fs before loading the file also produces this error:

`app.on('ready', () => {
    window = new BrowserWindow({ 
        width: 1400, 
        height: 900,
        backgroundColor: '#EAECEE'
    });

    if (fs.existsSync(path.join(process.cwd(), 'index.html'))) {
        window.loadURL(`file://${process.cwd()}/index.html`);
    } else {
        window.loadURL(`file://${process.cwd()}/some/other/path/index.html`);
    }
});
`

**Comment by stepbeta** [comment]
Having the same issue too. I'm using electron 1.6.11 and was tried with both spectron 3.7.2 and 3.6.4, but the issue is the same.

The code I run is the following:

```javascript
import { expect } from 'chai';
import { Application } from 'spectron';

const timeout = 10000;

describe('application launch', function () {
    let app;

    const startApp = function() {
        app = new Application({
            path: require('electron'),
            args: ['src/init'],
            startTimeout: timeout,
            waitTimeout: timeout,
        });
        return app.start().then(setupApp);
    };

    const setupApp = function() {
        return app.client.waitUntilWindowLoaded();
    };

    before(function() {
        this.timeout(timeout);
        return startApp();
    });

    after(function () {
        if (app && app.isRunning()) {
            return app.stop();
        }
    });

    it('shows hello world text on screen after launch', function () {
        return app.client.element('#title').then(function (text) {
            expect(text).to.equal('Hello world');
        });
    });
});
```

If I skip the setupApp function, then `text` is an object:

```javascript
{
  message: "An element could not be located on the page using the given search parameters.",
  selector: "#title",
  sessionId: "aa61e928c97596416a08b4c89b51dea4",
  state: "failure",
  status: 7,
  type: "NoSuchElement",
  value: null
}
```

This, given that my index.html only has a `<h1 id="title">Hello world</h1>` inside the body.
I also tried a few variations, such as `getText('#title')`, but the result is always the same.

**Comment by stepbeta** [comment]
The problem persists using electron@1.7.5

**Comment by stepbeta** [comment]
I also tried using electron@1.6.2 and spectron@3.6.0, which are the versions used by the electron-api-demos app. 

With these versions, `app.client.waitUntilWindowLoaded()` **does not** give an error! This clearly show it's a regression of some sort.

Even though this step helps it going, I still receive the "an element could not be located..." error object.

**Comment by stepbeta** [comment]
My last comment is true on windows, but on Ubuntu the issue persists even with those versions of electron and spectron.

**Comment by juddey** [comment]
Having the same issue with 3.7.2 on Elementary OS Loki (Ubuntu 16.04 base).

**Comment by TooBug** [comment]
Same issue on MacOS with spectron 3.7.2 and electron 1.6.11.

**Comment by TooBug** [comment]
Oh, I found the problem. It's because I opened the devtool in the main script. After disabling it, it works well.

**Comment by juddey** [comment]
@TooBug Confirmed that fixed my issue (I was loading devtools in my prod build also.)

**Comment by Smurf81** [comment]
@TooBug Thank you it save my day

**Comment by tansaku** [comment]
I had this issue too - perhaps we could add something to the README?

**Comment by cmdcolin** [comment]
This error can also occur if you set requireName to something and your app doesn't correspond properly.

E.g. I had set requireName: 'electronRequire' but my app forgot to change window.electronRequire = require;

```
            if(window.process&&process.versions&&process.versions.electron) {
                window.electronRequire = require;
                delete window.require;
            }
```

**Comment by karthik1407s** [comment]
Hi, 
@TooBug Is disabling the devtools in main script done from development end or is there a way to do it through spectron(test side).?

thanks in advance
Karthik

**Comment by codebytere** [comment]
Closing as this seems to have been resolved.

**Comment by albertotorresfoltyn** [comment]
Is not resolved, I still have the problem

**Comment by nj-neer** [comment]
Encountering a similar issue when **nodeIntegration** is set to **false**

Not sure if this is an expected behaviour 

```
this.browserWindow = new BrowserWindow({
      webPreferences: {
        nodeIntegration: false,
      }
    });
```

Failing test :
```
1) Opening editor
       opens a window:
     TypeError: waitUntilWindowLoaded Cannot read property 'isLoading' of undefined
      at waitUntil(<Function>, ) - C:\Users\cdelaunay\Desktop\Carnelian\node_modules\spectron\lib\application.js:229:17

  2) Opening editor
       "after each" hook for "opens a window":
     TypeError: Cannot read property 'exit' of undefined
      at Object.stopApp (test\hooks.js:26:29)
      at Context.afterEach (test\open_editor.js:11:17)
```

**Edit :** 

It will become very problematic when **nodeIntegration** will be set to false by default in **electron 5.0.0**
![image](https://user-images.githubusercontent.com/9463585/52409997-5beb6700-2ad7-11e9-8517-b7c39410b41e.png)

**Comment by scual** [comment]
The issue is still there in Electron 5.0.0 with Spectron 7.0.0

**Comment by roman01la** [comment]
The issue is still present :(

**Comment by oldmtn** [comment]
Report this issue if the libraries version is:
```
"electron": "^7.1.9",
"spectron": "^9.0.0"
"mocha": "^7.0.0",
```

It's ok if the libraries version is:
```
"electron": "1.8.2",
"mocha": "5.0.0",
"spectron": "3.8.0"
```

**Comment by sameoldmadness** [comment]
It looks the issue is that webdriverio cannot see the main window if it was initialized ~50 ms after the app ready event.

Here's the minimal reproducible example.

```js
// test.js
const electron = require('electron')
const { Application } = require('spectron')

const app = new Application({
  args: [
    '<cwd>/app.js',
  ],
  //   args: ['/Users/roman.paradeev/workspace/automation-tools/packages/electron-app/build/main.js'],
  path: electron,
})

Promise.resolve()
  .then(() => app.startChromeDriver())
  .then(() => app.createClient())
  .then(() => {
    return app.client
      .execute(function (requireName) {
        return typeof window[requireName] === 'function'
      }, 'require')
      .then(console.log)
  })

// app.js
const { app, BrowserWindow } = require('electron')

app.on('ready', () => {
  const w = new BrowserWindow()

  setTimeout(() => {
    w.loadURL('https://ya.ru')
  }, 5000)
})
```

As a workaround, one can load the blank page immediately. This fixes the aforementioned issue for me.

```
const { app, BrowserWindow } = require('electron')

app.on('ready', () => {
  const w = new BrowserWindow()

  w.loadURL('about:blank')

  setTimeout(() => {
    w.loadURL('https://ya.ru')
  }, 5000)
})
```

**Comment by VictorFouquet** [comment]
Having the same issue here with

main.js :

`
const { app, BrowserWindow } = require('electron')

function createWindow () {
  // Cree la fenetre du navigateur.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  win.loadFile('index.html')

  //win.webContents.openDevTools()
}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})`

DevDependecies in package.json :
`
"devDependencies": {
    "electron": "^10.1.3",
    "mocha": "^8.1.3",
    "spectron": "^12.0.0"
}`

test script : 

`
const { Application } = require('spectron')
const assert = require('assert')
const electronPath = require('electron')
const path = require('path')

const myApp =  new Application({
  path: electronPath,
  args: [path.join(__dirname, '..', 'main.js')]
})

const verifyWindowIsVisibleWithTitle = async (app) => {
  await app.start()
  
  try {

    const isVisible = await app.browserWindow.isVisible()
    assert.strictEqual(isVisible, true)

    const title = await app.client.getTitle()

    assert.strictEqual(title, 'My App')

  } catch (error) {

    console.error('Test failed', error.message)
  }

  await app.stop()
}

verifyWindowIsVisibleWithTitle(myApp)
`

Error is the same wether win.webContents.openDevTools() is commented or not :

Test failed Cannot read property 'isVisible' of undefined
(node:15762) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'remote' of undefined
    at /home/victorfouquet/Bureau/test-test/node_modules/spectron/lib/application.js:91:28
    at new Promise (<anonymous>)
    at Application.stop (/home/victorfouquet/Bureau/test-test/node_modules/spectron/lib/application.js:81:10)
    at verifyWindowIsVisibleWithTitle (/home/victorfouquet/Bureau/test-test/test/spec.js:77:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Ali-Baker** [comment]
I still have this issue

**Comment by rdandnayak** [comment]
I still am facing this issue 
![image](https://user-images.githubusercontent.com/816239/105445328-b3b81400-5c95-11eb-9b96-0e0112f0e2f7.png)

![image](https://user-images.githubusercontent.com/816239/105445409-dfd39500-5c95-11eb-86a7-ee71e1e05c60.png)

**Comment by AkatQuas** [comment]
![image](https://user-images.githubusercontent.com/24731539/126451675-c1ca278a-4aa3-4ca7-be29-41da7967ce9a.png)


Same issue with the following version


```json
{
  "devDependencies": {
    "electron": "13.1.7",
    "electron-rebuild": "~2.3.5",
    "spectron": "~15.0.0"
  }
}
```

My simple test file

```javascript
const assert = require('assert');
const path = require('path');
const electronPath = require('electron');
const { Application } = require('spectron');

const app = new Application({
  path: electronPath,
  env: {
    NODE_ENV: 'test',
  },
  args: [path.join(__dirname, '..')],
  webdriverOptions: {
    deprecationWarnings: false,
  },
});

app
  .start()
  .then(() => {
    return app.client.waitUntilWindowLoaded(5000);
  })
  .then(async () => {
    const visible = app.browserWindow.isVisible();
    assert.strictEqual(visible, true);
  })
  .catch((error) => {
    console.error('Test failed: ', error.message);
    console.error(error);
  });
```
